package daw2.javaClient;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * Generated source version: 3.0.0-milestone2
 * 
 */
public final class SimpleService_P1_Client {

    private final QName SERVICE_NAME = new QName("http://ttdev.com/ss", "SimpleService");

    public SimpleService_P1_Client() { }
    
    public String modifyDrupalTitle(String title) {
        URL wsdlURL = SimpleService_Service.WSDL_LOCATION;
        
        SimpleService_Service ss = new SimpleService_Service(wsdlURL, SERVICE_NAME);
        SimpleService port = ss.getP1();
        
        // System.out.println("Invoking concat...");
        java.lang.String _concat__return = port.concat(title, "");
        // System.out.println("concat.result=" + _concat__return);

        return _concat__return;
    }

}
